name: Java Apps - Run Tests and Package

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  test_and_build:
    name: Test and Build Samples
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Run Tests
        run: mvn clean test | tee test.log

      - name: Build Artifacts
        run: mvn clean package -Dmaven.test.skip=true

      - name: Set up Artifacts Directory
        run: mkdir -p artifacts && cp test.log target/*.jar artifacts/

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: package
          path: artifacts

